import type { Metadata } from "next";
import "./globals.css";

import { fontBody, fontDisplay } from "@/src/lib/fonts";
import { Footer, Header } from "@/src/components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontBody.variable} ${fontDisplay.variable} h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="px-4 sm:px-6 lg:px-8 pt-25 max-w-400 mx-auto flex-1 w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
