import type { Metadata } from "next";
import "./globals.css";

import { fontBody, fontDisplay } from "@/src/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontBody.variable} ${fontDisplay.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col max-w-300 mx-auto">{children}</body>
    </html>
  );
}
